name: CI - Tests

#
# Evento que controla quando a Action é disparada. Neste caso é disparado quando ocorre um
# push ou pull request em qualquer branch.
#
on:
  push:
  pull_request:

jobs:
  #
  # Este workflow tem apenas um job para Testes, , mas que será executadoem três sistemas operacionais
  # Linux, Windows e MacOs
  #
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    #
    # Sequencia de execução das tarefas do job.
    #
    steps:
      #
      # Checkout o repositório para poder ter acesso a ele.
      #
      - uses: actions/checkout@v2
      #
      # Configura os pacotes nas versões necessárias
      #
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      #
      # Instala todas as depedências do projeto.
      #
      - name: Install dependencies
        run: dotnet restore
      #
      # Executa todos os testes do projeto.
      #
      - name: Test
        # run: dotnet test --no-restore --verbosity normal
        run: dotnet test --configuration Release
